package mypojo;
// Generated Sep 28, 2021 9:20:21 PM by Hibernate Tools 4.3.1

import DAO.DAOPemilih;
import DAO.DAOVote;
import java.util.Date;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

/**
 * TblVote generated by hbm2java
 */
@ManagedBean
public class TblVote implements java.io.Serializable {
    
    private int idvote;
    private String kdvote;
    private String unqiduser;
    private Date tgljam;
    
    public TblVote() {
    }
    
    public TblVote(int idvote, String kdvote, String unqiduser, Date tgljam) {
        this.idvote = idvote;
        this.kdvote = kdvote;
        this.unqiduser = unqiduser;
        this.tgljam = tgljam;
    }
    
    public int getIdvote() {
        return this.idvote;
    }
    
    public void setIdvote(int idvote) {
        this.idvote = idvote;
    }

    public String getKdvote() {
        return this.kdvote;
    }
    
    public void setKdvote(String kdvote) {
        this.kdvote = kdvote;
    }

    public String getUnqiduser() {
        return this.unqiduser;
    }
    
    public void setUnqiduser(String unqiduser) {
        this.unqiduser = unqiduser;
    }

    public Date getTgljam() {
        return this.tgljam;
    }
    
    public void setTgljam(Date tgljam) {
        this.tgljam = tgljam;
    }
    
    public String doVote(Map<String, String> isinya) {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        HttpSession session = request.getSession();
        TblPemilih isiTbl = (TblPemilih) session.getAttribute("datalogin");
        String redirectPage = "user.xhtml?faces-redirect=true";
        
        DAOPemilih daoPem = new DAOPemilih();
        DAOVote dao = new DAOVote();
        this.kdvote = isinya.get("kdvote");
        this.tgljam = new Date();
        this.unqiduser = isiTbl.getUnqiduser();
        dao.add(this);
        isiTbl.setHasvote("1");
        
        daoPem.upd(isiTbl);
        session.setAttribute("datalogin", isiTbl);
//         pm = new DAOPemilih();
//        List<TblPemilih> isi = pm.getById(userid);
//        if(isi.isEmpty()) {
//            setRole("user");
//            setHasvote("0");
//            setUnqiduser(util.generateUUID());
//            pm.add(this);
//            redirectPage = "admin-pemilih.xhtml?faces-redirect=true";
//            return redirectPage;
//        }
//        errorMsg = "Userid has been taken.!";
//        error = true;
        return redirectPage;
    }
    
}
